### ISSUE TITLE
Requesting delete

### ISSUE THREAD

**Issue by DrBu7cher** [yunionio/sqlchemy#145]
**What would you like to be added**:
Delete by field function.
**Why is this needed**:
Because without delete, CRUD is only CRU. Why is delete not supported?
Best regards.

**Comment by swordqiu** [comment]
We will put this feature request in pipeline. Thanks for your feedback.

**Comment by swordqiu** [comment]
https://github.com/yunionio/sqlchemy/pull/157

batch_delete interface was added

**Comment by swordqiu** [comment]
@DrBu7cher
