### ISSUE TITLE
Running sqltest, problems with TEXT and UNSIGNED TINYINT types

### ISSUE THREAD

**Issue by kodabb** [yunionio/sqlchemy#61]
Hi I wanted to experiment with sqlchemy, but I can't see to make things work

The test file seems to not execute correctly https://github.com/yunionio/sqlchemy/blob/master/sqltest/main.go

```
panic: column "notes" type "TEXT CHARACTER SET 'utf8'" does not support having default value: "default notes"
```

When I remove that line from TestTable, and try it on my database, the creation is successful, but any subsequent operation fails with

```
[E 201004 20:44:02 sqlchemy.(*SSqlColumnInfo).toColumnSpec(sync.go:136)] unsupported type TINYINT UNSIGNED
```

Do you know if there is anything on my db configuration (mysql with innodb) that should be changed?
Thank you for any help about this problem

**Comment by yousong** [comment]
> Hi I wanted to experiment with sqlchemy, but I can't see to make things work
> 
> The test file seems to not execute correctly https://github.com/yunionio/sqlchemy/blob/master/sqltest/main.go

Thanks for your interest on sqlchemy!  I guess the sqltest program was mainly for test purposes during the initial prototype phase and now serves mainly as a sample.  Maybe we will need to setup CI test against real MySQL db in the future.  For now I opened a pull request to fix the issue.

> 
> ```
> panic: column "notes" type "TEXT CHARACTER SET 'utf8'" does not support having default value: "default notes"
> ```

The panic was caused by the fact MySQL does not support default values for TEXT columns.  The fix is to also add a "width" tag for the struct field to make it a VARCHAR column.

> 
> When I remove that line from TestTable, and try it on my database, the creation is successful, but any subsequent operation fails with
> 
> ```
> [E 201004 20:44:02 sqlchemy.(*SSqlColumnInfo).toColumnSpec(sync.go:136)] unsupported type TINYINT UNSIGNED
> ```

This one I am not sure.  The TINYINT UNSIGNED should be from the uint8 Age column, but sqlchemy should be able to handle it okay.  Maybe there are other changes to the code?

**Comment by kodabb** [comment]
Thanks for the quick reply, applied the changes and I can confirm the first panic is fixed.

About the second one, `TINYINT UNISIGNED`, I don't don't know if it's something to be changed on my database (I'm not very experienced on database tech). This is the file I'm trying, the only difference is the db connection line and parameters, here https://gist.github.com/kodabb/f5b78e1ff3b10e9b61668df707042ff3

The full panic follows, in case it helps

```
[E 201005 03:01:15 sqlchemy.(*SSqlColumnInfo).toColumnSpec(sync.go:136)] unsupported type TINYINT UNSIGNED
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x1309266]

goroutine 1 [running]:
yunion.io/x/sqlchemy.compareColumnSpec(0x0, 0x0, 0x1416740, 0xc0000c4850, 0xc0000cca00)
	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:174 +0x26
yunion.io/x/sqlchemy.diffCols.func1(0x3, 0x2, 0x138d401)
	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:184 +0x6b
sort.insertionSort_func(0xc0001bf048, 0xc00009dbf0, 0x0, 0x9)
	/usr/local/Cellar/go/1.15.2/libexec/src/sort/zfuncversion.go:12 +0xb4
sort.quickSort_func(0xc0001bf048, 0xc00009dbf0, 0x0, 0x9, 0x8)
	/usr/local/Cellar/go/1.15.2/libexec/src/sort/zfuncversion.go:158 +0x1f6
sort.Slice(0x133e4e0, 0xc0000a9c80, 0xc0001bf048)
	/usr/local/Cellar/go/1.15.2/libexec/src/sort/slice.go:17 +0xf3
yunion.io/x/sqlchemy.diffCols(0x13a730f, 0x9, 0xc0000cca00, 0x9, 0x10, 0xc0001d6a00, 0xc, 0x10, 0x0, 0x1609718, ...)
	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:183 +0xd6
yunion.io/x/sqlchemy.(*STableSpec).SyncSQL(0xc000221960, 0x4, 0xc000198200, 0xc0001ed1b0)
	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:304 +0x639
yunion.io/x/sqlchemy.(*STableSpec).Sync(0xc000221960, 0xc00019a0c0, 0x13a730f)
	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:398 +0x45
main.main()
	/Users/koda/src/sqlchemy_test/main.go:124 +0x153
```

**Comment by swordqiu** [comment]
> Thanks for the quick reply, applied the changes and I can confirm the first panic is fixed.
> 
> About the second one, `TINYINT UNISIGNED`, I don't don't know if it's something to be changed on my database (I'm not very experienced on database tech). This is the file I'm trying, the only difference is the db connection line and parameters, here https://gist.github.com/kodabb/f5b78e1ff3b10e9b61668df707042ff3
> 
> The full panic follows, in case it helps
> 
> ```
> [E 201005 03:01:15 sqlchemy.(*SSqlColumnInfo).toColumnSpec(sync.go:136)] unsupported type TINYINT UNSIGNED
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x1309266]
> 
> goroutine 1 [running]:
> yunion.io/x/sqlchemy.compareColumnSpec(0x0, 0x0, 0x1416740, 0xc0000c4850, 0xc0000cca00)
> 	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:174 +0x26
> yunion.io/x/sqlchemy.diffCols.func1(0x3, 0x2, 0x138d401)
> 	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:184 +0x6b
> sort.insertionSort_func(0xc0001bf048, 0xc00009dbf0, 0x0, 0x9)
> 	/usr/local/Cellar/go/1.15.2/libexec/src/sort/zfuncversion.go:12 +0xb4
> sort.quickSort_func(0xc0001bf048, 0xc00009dbf0, 0x0, 0x9, 0x8)
> 	/usr/local/Cellar/go/1.15.2/libexec/src/sort/zfuncversion.go:158 +0x1f6
> sort.Slice(0x133e4e0, 0xc0000a9c80, 0xc0001bf048)
> 	/usr/local/Cellar/go/1.15.2/libexec/src/sort/slice.go:17 +0xf3
> yunion.io/x/sqlchemy.diffCols(0x13a730f, 0x9, 0xc0000cca00, 0x9, 0x10, 0xc0001d6a00, 0xc, 0x10, 0x0, 0x1609718, ...)
> 	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:183 +0xd6
> yunion.io/x/sqlchemy.(*STableSpec).SyncSQL(0xc000221960, 0x4, 0xc000198200, 0xc0001ed1b0)
> 	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:304 +0x639
> yunion.io/x/sqlchemy.(*STableSpec).Sync(0xc000221960, 0xc00019a0c0, 0x13a730f)
> 	/Users/koda/pkg/mod/yunion.io/x/sqlchemy@v0.0.0-20200909073353-606d1fe76db5/sync.go:398 +0x45
> main.main()
> 	/Users/koda/src/sqlchemy_test/main.go:124 +0x153
> ```

It seemed you were using an incompatible version of mysql.

I've added compatible codes to support a column type of `tinyint unsigned'. Please try this PR #63

**Comment by kodabb** [comment]
@swordqiu thank you for the PR, i've just tested your PR - the panic is gone, however the CheckSync() calls are failing:

```
[I 201005 12:56:52 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `age` TINYINT UNSIGNED DEFAULT 18(primary:false) => `age` TINYINT(4) UNSIGNED DEFAULT 18(primary:false)
[I 201005 12:56:52 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `version` INT NOT NULL DEFAULT 0(primary:false) => `version` INT(11) NOT NULL DEFAULT 0(primary:false)
[D 201005 12:56:52 sqlchemy.(*STableSpec).SyncSQL(sync.go:279)] table age_tbl not created yet
[I 201005 12:56:53 sqlchemy.diffCols(sync.go:209)] UPDATE age_tbl: `age` INT(primary:false) => `age` INT(11)(primary:false)
ALTER TABLE `age_tbl` MODIFY `age` INT(11);
[F 201005 12:56:53 sqlchemy.(*STableSpec).CheckSync(sync.go:421)] DB table "age_tbl" not in sync
```

If i remove the the calls it seems to be working as expected (i think)

```
[I 201005 12:57:06 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `age` TINYINT UNSIGNED DEFAULT 18(primary:false) => `age` TINYINT(4) UNSIGNED DEFAULT 18(primary:false)
[I 201005 12:57:06 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `version` INT NOT NULL DEFAULT 0(primary:false) => `version` INT(11) NOT NULL DEFAULT 0(primary:false)
[I 201005 12:57:07 sqlchemy.diffCols(sync.go:209)] UPDATE age_tbl: `age` INT(primary:false) => `age` INT(11)(primary:false)
[D 201005 12:57:07 sqlchemy.(*STableSpec).SyncSQL(sync.go:279)] table ticket_tbl not created yet
SELECT t1.id, t2.age FROM `testtable` AS `t1` JOIN `age_tbl` AS `t2` ON (`t1`.`id` = `t2`.`user_id`) AND (`t2`.`age` >= ( ? )) WHERE `t1`.`id` LIKE ( ? ) ORDER BY `t2`.`age` ASC LIMIT 10
[20 123%]
SELECT `t3`.`id`, `t3`.`age` FROM (SELECT t1.id, t2.age FROM `testtable` AS `t1` JOIN `age_tbl` AS `t2` ON (`t1`.`id` = `t2`.`user_id`) AND (`t2`.`age` >= ( ? )) WHERE `t1`.`id` LIKE ( ? ) ORDER BY `t2`.`age` ASC LIMIT 10) AS `t3` ORDER BY `t3`.`id` DESC
[20 123%]
dt1 after insert:  {1655fa15-0051-4e5f-8b23-ede3619bae72 Test  0 {"name":"Test"} {"age":24,"id":"123456"} 2020-10-05 10:57:08 +0000 UTC 2020-10-05 10:57:08 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC false default notes}
{1 1655fa15-0051-4e5f-8b23-ede3619bae72 2020-10-05 10:57:08 +0000 UTC}
Count:  0
Count:  0
map[age:0 compond:{"age":24,"id":"123456"} created_at:2020-10-05 10:57:08 deleted:0 deleted_at: gender: id:1655fa15-0051-4e5f-8b23-ede3619bae72 info:{"name":"Test"} name:Test notes:default notes updated_at:2020-10-05 10:57:08 version:0]
Before update {1655fa15-0051-4e5f-8b23-ede3619bae72 Test  0 {"name":"Test"} {"age":24,"id":"123456"} 2020-10-05 10:57:08 +0000 UTC 2020-10-05 10:57:08 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC false default notes}
[E 201005 12:57:10 main.main(main.go:223)] incremental faild sql: no rows in result set
After update:  {"age":10,"compond":{"age":80,"id":"998822333"},"created_at":"2020-10-05T10:57:08.000000Z","deleted":false,"id":"1655fa15-0051-4e5f-8b23-ede3619bae72","info":{"name":"Test"},"name":"New name 4","notes":"default notes","updated_at":"2020-10-05T10:57:09.000000Z","version":1}
[I 201005 12:57:10 main.main(main.go:236)] Start SQuery ALL
[I 201005 12:57:11 main.main(main.go:243)] SQuery all no error 1
dt4  {"age":10,"compond":{"age":80,"id":"998822333"},"created_at":"2020-10-05T10:57:08.000000Z","deleted":false,"id":"1655fa15-0051-4e5f-8b23-ede3619bae72","info":{"name":"Test"},"name":"New name 4","notes":"default notes","updated_at":"2020-10-05T10:57:09.000000Z","version":1}
SELECT id FROM ((SELECT t1.id FROM `testtable` AS `t1`) UNION (SELECT t9.id FROM `ticket_tbl` AS `t9`) LIMIT 20 OFFSET 10) AS `t10`
[I 201005 12:57:11 main.main(main.go:266)] Test: []```

I am using mysql 8.0.21 on ubuntu, happy to run more tests if it helps or try another version and provide more details

relatedly to `CheckSync()`, may i suggest to remove the `Fatalf` calls and change them to return errors? These function stop the execution of the main software in an abrupt way, without letting `defer`s being called. Ideally this pattern should be followed

```
	ticketSpec := sqlchemy.NewTableSpecFromStruct(Ticket{}, "ticket_tbl")
	ticketSpec.Sync()
	err := ticketSpec.CheckSync()
        if err != nil {
            // let the user handle error case, for example with log.Fatalf(err) or retries or returns
        }
```

**Comment by swordqiu** [comment]
> @swordqiu thank you for the PR, i've just tested your PR - the panic is gone, however the CheckSync() calls are failing:
> 
> ```
> [I 201005 12:56:52 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `age` TINYINT UNSIGNED DEFAULT 18(primary:false) => `age` TINYINT(4) UNSIGNED DEFAULT 18(primary:false)
> [I 201005 12:56:52 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `version` INT NOT NULL DEFAULT 0(primary:false) => `version` INT(11) NOT NULL DEFAULT 0(primary:false)
> [D 201005 12:56:52 sqlchemy.(*STableSpec).SyncSQL(sync.go:279)] table age_tbl not created yet
> [I 201005 12:56:53 sqlchemy.diffCols(sync.go:209)] UPDATE age_tbl: `age` INT(primary:false) => `age` INT(11)(primary:false)
> ALTER TABLE `age_tbl` MODIFY `age` INT(11);
> [F 201005 12:56:53 sqlchemy.(*STableSpec).CheckSync(sync.go:421)] DB table "age_tbl" not in sync
> ```
> 
> If i remove the the calls it seems to be working as expected (i think)
> 
> ```
> [I 201005 12:57:06 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `age` TINYINT UNSIGNED DEFAULT 18(primary:false) => `age` TINYINT(4) UNSIGNED DEFAULT 18(primary:false)
> [I 201005 12:57:06 sqlchemy.diffCols(sync.go:209)] UPDATE testtable: `version` INT NOT NULL DEFAULT 0(primary:false) => `version` INT(11) NOT NULL DEFAULT 0(primary:false)
> [I 201005 12:57:07 sqlchemy.diffCols(sync.go:209)] UPDATE age_tbl: `age` INT(primary:false) => `age` INT(11)(primary:false)
> [D 201005 12:57:07 sqlchemy.(*STableSpec).SyncSQL(sync.go:279)] table ticket_tbl not created yet
> SELECT t1.id, t2.age FROM `testtable` AS `t1` JOIN `age_tbl` AS `t2` ON (`t1`.`id` = `t2`.`user_id`) AND (`t2`.`age` >= ( ? )) WHERE `t1`.`id` LIKE ( ? ) ORDER BY `t2`.`age` ASC LIMIT 10
> [20 123%]
> SELECT `t3`.`id`, `t3`.`age` FROM (SELECT t1.id, t2.age FROM `testtable` AS `t1` JOIN `age_tbl` AS `t2` ON (`t1`.`id` = `t2`.`user_id`) AND (`t2`.`age` >= ( ? )) WHERE `t1`.`id` LIKE ( ? ) ORDER BY `t2`.`age` ASC LIMIT 10) AS `t3` ORDER BY `t3`.`id` DESC
> [20 123%]
> dt1 after insert:  {1655fa15-0051-4e5f-8b23-ede3619bae72 Test  0 {"name":"Test"} {"age":24,"id":"123456"} 2020-10-05 10:57:08 +0000 UTC 2020-10-05 10:57:08 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC false default notes}
> {1 1655fa15-0051-4e5f-8b23-ede3619bae72 2020-10-05 10:57:08 +0000 UTC}
> Count:  0
> Count:  0
> map[age:0 compond:{"age":24,"id":"123456"} created_at:2020-10-05 10:57:08 deleted:0 deleted_at: gender: id:1655fa15-0051-4e5f-8b23-ede3619bae72 info:{"name":"Test"} name:Test notes:default notes updated_at:2020-10-05 10:57:08 version:0]
> Before update {1655fa15-0051-4e5f-8b23-ede3619bae72 Test  0 {"name":"Test"} {"age":24,"id":"123456"} 2020-10-05 10:57:08 +0000 UTC 2020-10-05 10:57:08 +0000 UTC 0 0001-01-01 00:00:00 +0000 UTC false default notes}
> [E 201005 12:57:10 main.main(main.go:223)] incremental faild sql: no rows in result set
> After update:  {"age":10,"compond":{"age":80,"id":"998822333"},"created_at":"2020-10-05T10:57:08.000000Z","deleted":false,"id":"1655fa15-0051-4e5f-8b23-ede3619bae72","info":{"name":"Test"},"name":"New name 4","notes":"default notes","updated_at":"2020-10-05T10:57:09.000000Z","version":1}
> [I 201005 12:57:10 main.main(main.go:236)] Start SQuery ALL
> [I 201005 12:57:11 main.main(main.go:243)] SQuery all no error 1
> dt4  {"age":10,"compond":{"age":80,"id":"998822333"},"created_at":"2020-10-05T10:57:08.000000Z","deleted":false,"id":"1655fa15-0051-4e5f-8b23-ede3619bae72","info":{"name":"Test"},"name":"New name 4","notes":"default notes","updated_at":"2020-10-05T10:57:09.000000Z","version":1}
> SELECT id FROM ((SELECT t1.id FROM `testtable` AS `t1`) UNION (SELECT t9.id FROM `ticket_tbl` AS `t9`) LIMIT 20 OFFSET 10) AS `t10`
> [I 201005 12:57:11 main.main(main.go:266)] Test: []
> ```
> 
> I am using mysql 8.0.21 on ubuntu, happy to run more tests if it helps or try another version and provide more details
> 

The error was due to the fact that mysql 8.0.21 does not carry a default display width value for integer types in 'show full columns' results. I managed to setup a mysql 8.0.21 instance, and  have made the necessary changes to accomendate the differences. We mostly tested our codes against mariadb 5.7 or above. Since mysql 8 is still widely used, we would like to include mysql 8 in our future test cases.

Please checkout this PR #63 and try again.

> relatedly to `CheckSync()`, may i suggest to remove the `Fatalf` calls and change them to return errors? These function stop the execution of the main software in an abrupt way, without letting `defer`s being called. Ideally this pattern should be followed
> 
> ```
> 	ticketSpec := sqlchemy.NewTableSpecFromStruct(Ticket{}, "ticket_tbl")
> 	ticketSpec.Sync()
> 	err := ticketSpec.CheckSync()
>         if err != nil {
>             // let the user handle error case, for example with log.Fatalf(err) or retries or returns
>         }
> ```

Thanks for the suggestion. It sounds appropriate for a 3rd-party library. Since the change may impact the expected behavior of our other repos that relies on this repo. We are going to made this change in another PR.

**Comment by kodabb** [comment]
> Please checkout this PR #63 and try again.

I tried it, looks like it's working now! Thank you

> Thanks for the suggestion. It sounds appropriate for a 3rd-party library. Since the change may impact the expected behavior of our other repos that relies on this repo. We are going to made this change in another PR.

sounds good, would you like me to open a separate issue for this as well?

**Comment by swordqiu** [comment]
> sounds good, would you like me to open a separate issue for this as well?

Sure, please!

**Comment by kodabb** [comment]
great, opened #64 and closing this one, thank you
