### ISSUE TITLE
Change API to avoid using log.Fatalf in the code

### ISSUE THREAD

**Issue by kodabb** [yunionio/sqlchemy#64]
While filing #61 I noticed there are a few log.Fatalf calls throughout the code, and I wanted to suggest to remove them and change the logic to just return errors? The reason for these request is that Fatalf calls stop the execution of the main software in an abrupt way, without letting defers being called.

Since sqlchemy can be used as a library, ideally this pattern should be followed

	ticketSpec := sqlchemy.NewTableSpecFromStruct(Ticket{}, "ticket_tbl")
	ticketSpec.Sync()
	err := ticketSpec.CheckSync()
	if err != nil {
		// let the user handle error case, for example with log.Fatalf(err) or retries or returns
	}

The README.md file seem to suggest this behaviour as well

**Comment by swordqiu** [comment]
This issue has been addressed by PR #65 . Many thanks.

**Comment by kodabb** [comment]
this was addressed, thank you
